# PNMPI
PNMPI_INC_PATH		=    /g/g90/sato5/opt/include/
PNMPI_BIN_PATH  	=    /g/g90/sato5/opt/bin
PNMPI_MOD_LIB_PATH 	=    /g/g90/sato5/opt/lib/pnmpi-modules
PNMPI_LIB_PATH 	        =    /g/g90/sato5/opt/lib


# MPI C++ compiler
CXX 		= mpicc  -fPIC -rdynamic -g
MPIXX		= $(CXX)
CC		= $(CXX)
MPICC		= $(CXX)
		

# Passed to compiler
OPT_LEVEL	= -O2
DEBUG_LEVEL	= -g -std=c++0x -pthread 
#DEBUG_LEVEL	= -g -pthread 
EXTRA_CCFLAGS	= -Wall
CXXFLAGS	= $(OPT_LEVEL) $(DEBUG_LEVEL) $(EXTRA_CCFLAGS) 
CCFLAGS		= $(CXXFLAGS) 

# Passed to the C pre-processor
CPPFLAGS        = -I./ -I../src
CFLAGS		= $(CPPFLAGS)

# Passed to the linker
LDFLAGS         = -L./ -lstdc++ 

# Link with these libraries
LDLIBS          =

# Installation path
prefix		= ./lib

